### ISSUE TITLE
reftex-toc goto creates window split

### ISSUE THREAD

**Issue by CThuleHansen** [DamienCassou/RefTeX#1]
When goto is executed on reftex-toc then a vsplit is performed if only 1 buffer is open, and the file is presented to window to the right.

If 2 buffers are open, then the active window from where the toc was spawned is used to display the buffer. 

I would like it to always use the active window from where the toc was spawned. 
Is this possible?

My current suboptimal workaround is
```  (add-hook 'reftex-toc-mode-hook 'spacemacs/toggle-maximize-buffer)```

**Comment by DamienCassou** [comment]
I'm sorry, but this repository is a very old clone. Please refer to https://www.gnu.org/software/auctex/reftex.html for the proper links. I will close the repository.
